[package]
name = "world-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu-noboiler = "0.1.6"
wgpu-shapes = "0.1.0"
